In [1]:
import pandas as pd
import numpy as np
import random

random.seed(42)
np.random.seed(42)

categories = ["IT Support", "HR", "Sales", "Finance", "General"]
priorities = ["low", "medium", "high", "urgent"]

names = ["Alice", "Bob", "Charlie", "David", "Emma", "Fatima", "George", "Hari", "Isha", "John",
         "Kiran", "Liu", "Maria", "Nikhil", "Olivia", "Pranav", "Quinn", "Ravi", "Sophia"]

domains = ["company.com", "customer.com", "vendor.com", "partner.com"]
systems = ["VPN", "email server", "HR portal", "CRM system", "inventory system", "billing portal"]
issues = ["timeout error", "access denied", "server not responding", "unknown error code 500",
          "page not loading", "login failed multiple times"]

products = ["Enterprise Suite", "Analytics Pro", "Cloud Manager", "HRMS Plus", "Sales Booster"]
invoice_numbers = [f"{1000 + i}" for i in range(200)]
dates = ["this week", "last week", "yesterday", "today morning", "end of this month"]

def random_email_address(name=None, domain=None):
    if name is None:
        name = random.choice(names)
    if domain is None:
        domain = random.choice(domains)
    handle = name.lower()
    handle = handle.replace(" ", ".")
    return f"{handle}@{domain}"

def choose_priority(category, is_urgent=False):
    if is_urgent:
        return np.random.choice(["high", "urgent"], p=[0.4, 0.6])
    if category == "IT Support":
        return np.random.choice(priorities, p=[0.1, 0.4, 0.4, 0.1])
    if category == "Finance":
        return np.random.choice(priorities, p=[0.2, 0.4, 0.3, 0.1])
    if category == "Sales":
        return np.random.choice(priorities, p=[0.3, 0.4, 0.2, 0.1])
    if category == "HR":
        return np.random.choice(priorities, p=[0.2, 0.5, 0.2, 0.1])
    return np.random.choice(priorities, p=[0.3, 0.4, 0.2, 0.1])

# Templates per category
templates = {
    "IT Support": [
        {
            "subject": "Unable to access {system}",
            "body": """Hi IT team,

I am unable to access the {system} since {time}. I keep getting a {issue}.
Could you please help me resolve this?

Thanks,
{name}
""",
            "reply": """Hi {name},

Thanks for contacting the IT helpdesk. We are looking into the {system} issue ({issue}) and will update you within the next {sla}.

Best regards,
IT Support Team
"""
        },
        {
            "subject": "Laptop running very slow",
            "body": """Hello,

My work laptop has been extremely slow today, especially when using the {system}.
This is affecting my work. Please check and advise.

Regards,
{name}
""",
            "reply": """Hi {name},

Thank you for reporting the performance issue. Please restart your laptop and ensure all pending updates are installed. 
If the problem persists, our team will schedule a remote session within {sla}.

Best,
IT Support
"""
        },
        {
            "subject": "Password reset request",
            "body": """Hi,

I forgot my password for the {system} and I'm unable to log in.
Can you please reset it or guide me through the process?

Thanks,
{name}
""",
            "reply": """Hi {name},

We have initiated a password reset for your {system} account. 
You will receive a separate email with instructions shortly.

Regards,
IT Support
"""
        },
    ],
    "HR": [
        {
            "subject": "Leave policy clarification",
            "body": """Hi HR team,

Could you please clarify the annual leave carry-forward policy for this year?
I want to plan my vacation accordingly.

Regards,
{name}
""",
            "reply": """Hi {name},

Thank you for reaching out. Our annual leave carry-forward policy allows employees to carry forward up to 10 unused leave days to the next calendar year.

Best regards,
HR Team
"""
        },
        {
            "subject": "New hire onboarding request",
            "body": """Hello HR,

We have a new joiner starting next Monday in the {department} team.
Please initiate the onboarding and share the checklist.

Thanks,
{name}
""",
            "reply": """Hi {name},

Thank you for informing us. We have initiated the onboarding process for the new joiner in the {department} team.
Our team will share the onboarding checklist shortly.

Regards,
HR
"""
        },
        {
            "subject": "Request for experience letter",
            "body": """Dear HR,

I would like to request an official experience letter for my tenure at the company.
Please let me know if any additional details are required.

Thank you,
{name}
""",
            "reply": """Dear {name},

Thank you for your request. We will process your experience letter and share it with you within {sla}.

Best regards,
HR Department
"""
        },
    ],
    "Sales": [
        {
            "subject": "Inquiry about {product} pricing",
            "body": """Hello,

I am interested in learning more about the pricing and plans for your product {product}.
Could you share the enterprise pricing details?

Regards,
{name}
""",
            "reply": """Hello {name},

Thank you for your interest in {product}. Our sales team will share the detailed pricing plans and options with you shortly.

Best regards,
Sales Team
"""
        },
        {
            "subject": "Demo request for {product}",
            "body": """Hi,

We would like to schedule a demo of {product} for our management team sometime {time}.
Please let us know your availability.

Thanks,
{name}
""",
            "reply": """Hi {name},

Thank you for requesting a demo of {product}. Our team will contact you to confirm a suitable date and time {time}.

Regards,
Sales
"""
        },
        {
            "subject": "Follow-up on proposal",
            "body": """Hello,

This is a follow-up regarding the proposal you shared last {time} for the {product}.
We are reviewing it and have a few questions.

Best,
{name}
""",
            "reply": """Hello {name},

Thank you for your follow-up. We are happy to clarify any questions you may have regarding the {product} proposal. 
Our representative will connect with you shortly.

Best regards,
Sales Team
"""
        },
    ],
    "Finance": [
        {
            "subject": "Pending invoice #{invoice}",
            "body": """Dear Finance team,

This is a reminder that invoice #{invoice} is still pending for payment.
The due date was {time}. Please provide an update on the payment status.

Sincerely,
{name}
""",
            "reply": """Dear {name},

Thank you for the reminder regarding invoice #{invoice}. Our finance team is reviewing the payment and will process it at the earliest.

Best regards,
Finance Team
"""
        },
        {
            "subject": "Clarification on reimbursement policy",
            "body": """Hi Finance,

Could you please clarify the reimbursement policy for travel and accommodation expenses?
I recently completed a business trip and want to submit my claims correctly.

Thanks,
{name}
""",
            "reply": """Hi {name},

Thank you for reaching out. Our reimbursement policy covers reasonable travel and accommodation expenses with valid receipts.
We will share the detailed policy document with you.

Regards,
Finance
"""
        },
        {
            "subject": "Salary credit not received",
            "body": """Hello,

I have not yet received my salary credit for this month in my bank account.
Could you please check and confirm?

Regards,
{name}
""",
            "reply": """Hello {name},

We apologize for the inconvenience. Our team is checking the salary disbursement status and will update you within {sla}.

Best,
Payroll Team
"""
        },
    ],
    "General": [
        {
            "subject": "Access to meeting room",
            "body": """Hi Admin,

Could you please help me book a meeting room for {time} tomorrow for a client discussion?

Thanks,
{name}
""",
            "reply": """Hi {name},

We have noted your request and will book a suitable meeting room for your client discussion at {time} tomorrow.

Best regards,
Admin Team
"""
        },
        {
            "subject": "Feedback about cafeteria services",
            "body": """Hello,

I wanted to share some feedback regarding the cafeteria services.
The food quality has improved, but the waiting time during lunch hours is still quite long.

Regards,
{name}
""",
            "reply": """Hello {name},

Thank you for sharing your feedback about the cafeteria services. We appreciate your input and will work with the vendor to reduce waiting times.

Best,
Admin
"""
        },
        {
            "subject": "Request for general information",
            "body": """Hi,

I would like to know more about the internal training programs available for employees this quarter.

Thanks,
{name}
""",
            "reply": """Hi {name},

Thank you for your interest in our internal training programs. We will share the list of available sessions and enrollment details with you.

Best regards,
L&D Team
"""
        },
    ],
}

def generate_email_row(i):
    category = random.choice(categories)
    template = random.choice(templates[category])
    
    name = random.choice(names)
    system = random.choice(systems)
    issue = random.choice(issues)
    product = random.choice(products)
    time = random.choice(dates)
    invoice = random.choice(invoice_numbers)
    department = random.choice(["Engineering", "Marketing", "Sales", "HR", "Finance"])
    sla = random.choice(["4 hours", "8 hours", "1 business day", "2 business days"])
    
    is_urgent = "not received" in template["body"] or "unable to access" in template["subject"].lower()
    priority = choose_priority(category, is_urgent=is_urgent)
    
    subject = template["subject"].format(
        system=system,
        product=product,
        time=time,
        invoice=invoice,
        department=department
    )
    
    body = template["body"].format(
        name=name,
        system=system,
        issue=issue,
        product=product,
        time=time,
        invoice=invoice,
        department=department
    )
    
    reply = template["reply"].format(
        name=name,
        system=system,
        issue=issue,
        product=product,
        time=time,
        invoice=invoice,
        department=department,
        sla=sla
    )
    
    sender = random_email_address(name)
    # simple guess: route by category
    if category == "IT Support":
        receiver = "support@company.com"
    elif category == "HR":
        receiver = "hr@company.com"
    elif category == "Sales":
        receiver = "sales@company.com"
    elif category == "Finance":
        receiver = "finance@company.com"
    else:
        receiver = "contact@company.com"
    
    return {
        "id": i,
        "from": sender,
        "to": receiver,
        "subject": subject,
        "body": body,
        "category": category,
        "priority": priority,
        "reply_text": reply,
    }

# Generate dataset
# Generate dataset
N = 2500  # bigger dataset
rows = [generate_email_row(i+1) for i in range(N)]
df = pd.DataFrame(rows)

# Add combined text column used for training
df["text"] = (df["subject"].fillna("") + " " + df["body"].fillna("")).str.strip()

print(df.shape)
df.head()

(2500, 9)

,id,from,to,subject,body,category,priority,reply_text,text
0,1,isha@partner.com,support@company.com,Unable to access email server,"Hi IT team,\n\nI am unable to access the email...",IT Support,high,"Hi Isha,\n\nThanks for contacting the IT helpd...","Unable to access email server Hi IT team,\n\nI..."
1,2,charlie@partner.com,support@company.com,Unable to access email server,"Hi IT team,\n\nI am unable to access the email...",IT Support,urgent,"Hi Charlie,\n\nThanks for contacting the IT he...","Unable to access email server Hi IT team,\n\nI..."
2,3,sophia@customer.com,hr@company.com,New hire onboarding request,"Hello HR,\n\nWe have a new joiner starting nex...",HR,high,"Hi Sophia,\n\nThank you for informing us. We h...","New hire onboarding request Hello HR,\n\nWe ha..."
3,4,charlie@partner.com,sales@company.com,Inquiry about Cloud Manager pricing,"Hello,\n\nI am interested in learning more abo...",Sales,medium,"Hello Charlie,\n\nThank you for your interest ...","Inquiry about Cloud Manager pricing Hello,\n\n..."
4,5,maria@company.com,contact@company.com,Access to meeting room,"Hi Admin,\n\nCould you please help me book a m...",General,low,"Hi Maria,\n\nWe have noted your request and wi...","Access to meeting room Hi Admin,\n\nCould you ..."

In [2]:
df.to_csv("emails.csv", index=False)
print("Saved emails.csv with shape:", df.shape)

Saved emails.csv with shape: (2500, 9)

In [3]:
df = pd.read_csv("emails.csv")

In [4]:
import pandas as pd
import numpy as np
import random

random.seed(42)
np.random.seed(42)

categories = ["IT Support", "HR", "Sales", "Finance", "General"]
...

Ellipsis

In [5]:
df["text"] = (df["subject"].fillna("") + " " + df["body"].fillna("")).str.strip()
df.head()

,id,from,to,subject,body,category,priority,reply_text,text
0,1,isha@partner.com,support@company.com,Unable to access email server,"Hi IT team,\n\nI am unable to access the email...",IT Support,high,"Hi Isha,\n\nThanks for contacting the IT helpd...","Unable to access email server Hi IT team,\n\nI..."
1,2,charlie@partner.com,support@company.com,Unable to access email server,"Hi IT team,\n\nI am unable to access the email...",IT Support,urgent,"Hi Charlie,\n\nThanks for contacting the IT he...","Unable to access email server Hi IT team,\n\nI..."
2,3,sophia@customer.com,hr@company.com,New hire onboarding request,"Hello HR,\n\nWe have a new joiner starting nex...",HR,high,"Hi Sophia,\n\nThank you for informing us. We h...","New hire onboarding request Hello HR,\n\nWe ha..."
3,4,charlie@partner.com,sales@company.com,Inquiry about Cloud Manager pricing,"Hello,\n\nI am interested in learning more abo...",Sales,medium,"Hello Charlie,\n\nThank you for your interest ...","Inquiry about Cloud Manager pricing Hello,\n\n..."
4,5,maria@company.com,contact@company.com,Access to meeting room,"Hi Admin,\n\nCould you please help me book a m...",General,low,"Hi Maria,\n\nWe have noted your request and wi...","Access to meeting room Hi Admin,\n\nCould you ..."

In [6]:
df.to_csv("emails.csv", index=False)
print("Saved emails.csv with shape:", df.shape)

df = pd.read_csv("emails.csv")

Saved emails.csv with shape: (2500, 9)